apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: cc-resilient-bucket-jonizeng-infra
  namespace: config-control
  labels:
    env: demo
    site: primary
  annotations:
    cnrm.cloud.google.com/deletion-policy: "delete"
spec:
  location: US
  storageClass: STANDARD
