apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: cc-resilient-bucket-jonizeng-infra
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/deletion-policy: "delete"
spec:
  location: EU
  storageClass: STANDARD
